# nginx-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: webapp
spec:
  containers:
  - name: nginx-container
    image: nginx:latest  # Specifies the NGINX image to use
    ports:
    - containerPort: 80  # Defines the port the container listens on (NGINX default)
      protocol: TCP
